base_uri: 'timeseries'
max_processing_time: 10000
max_concurrent_jobs: 1
name: 'SKOPE Development / Testing API'
store:
  base_path: 'data'
  template: 'data/{dataset_id}/{variable_id}'
  uncertainty_template: 'data/{dataset_id}/{variable_id}_uncertainty'
tile_server_url: 'http://titiler:80'
storage_base_url: '/data/'
