version: '3.7'
services:
  server:
    build:
      context: timeseries
    restart: always
  geoserver:
    environment:
      GEOSERVER_ADMIN_PASSWORD_FILE: /run/secrets/geoserver_admin_password
      GEOSERVER_ADMIN_USER: skope
      STABLE_EXTENSIONS: importer-plugin
    image: kartoza/geoserver:2.19.2
