version: '3.7'
services:
  server:
    build:
      args:
        ENVIR: dev
      dockerfile: deploy/Dockerfile
    image: openskope/server/dev:latest
    volumes:
      - ./timeseries:/code
    ports:
    - "127.0.0.1:8001:8000"
  geoserver:
    ports:
    - "127.0.0.1:8600:8080"