version: '3.7'
services:
  server:
    build:
      args:
        ENVIR: dev
      dockerfile: deploy/Dockerfile
    image: openskope/server/dev:latest
    volumes:
      - .:/code
    ports:
    - "127.0.0.1:8002:8000"