version: '3.8'
services:
  server:
    build:
      context: timeseries
    restart: always
  geoserver:
    environment:
      GEOSERVER_ADMIN_PASSWORD_FILE: /run/secrets/geoserver_admin_password
      GEOSERVER_ADMIN_USER: skope
      STABLE_EXTENSIONS: importer-plugin
      TOMCAT_EXTRAS: "false"
    image: kartoza/geoserver:2.20.0
