services:
  server:
    build:
      args:
        ENVIRONMENT: dev
      dockerfile: deploy/Dockerfile
    image: openskope/skope-api:latest
    volumes:
      - ./timeseries:/code
    ports:
    - "127.0.0.1:8001:8000"
  geoserver:
    ports:
    - "127.0.0.1:8600:8080"
