version: '3.8'
services:
  server:
    build:
      args:
        ENVIR: prod
      dockerfile: deploy/Dockerfile
    # may need additional config to deal with X-Forwarded-*
    # https://docs.gunicorn.org/en/stable/deploy.html#nginx-configuration
    command:
      - gunicorn
      - "--bind"
      - "0.0.0.0:8000"
      - "--workers"
      - "4"
      - "--worker-class"
      - "uvicorn.workers.UvicornWorker"
      - "app.main:app"
    environment:
      FORWARDED_ALLOW_IPS: '*'
    image: openskope/skope-api:latest
    volumes:
      - ./timeseries:/code
      - /projects/skope/datasets:/data
    ports:
    - "0.0.0.0:8001:8000"
  geoserver:
    restart: always
    ports:
      - 0.0.0.0:8600:8080/tcp
    environment:
      EXISTING_DATA_DIR: "true"
      CSRF_WHITELIST: "geoserver.openskope.org"
      GEOSERVER_DATA_DIR: "/data/geoserver/state"
    volumes:
      - /projects/skope/datasets:/projects/skope/datasets:rw
      - /data/geoserver/state:/data/geoserver/state:rw
      - ./geoserver/docker/secrets/geoserver_admin_password:/run/secrets/geoserver_admin_password:ro
      - ./geoserver/settings:/settings:rw
