name: Test SKOPE Time Series API

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r timeseries/deploy/requirements/base.txt -r timeseries/deploy/requirements/dev.txt
          make -C timeseries/tests node_modules
      - name: Run the tests
        run: |
          trap '[ -n "$(jobs -pr)" ] && kill $(jobs -pr)' INT QUIT TERM EXIT
          cd timeseries
          ENVIR=dev pytest
          # ENVIR=dev uvicorn --port 8001 app.main:app &
          # cd ..
          # ./configure dev
          # make test-integration
