name: Test SKOPE Time Series API

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r deploy/requirements/base.txt -r deploy/requirements/dev.txt
      - name: Run the tests
        run: |
          SETTINGS_MODULE=app.settings.dev pytest
