name: Test SKOPE Time Series API

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          ./configure dev
          pip install -r timeseries/deploy/requirements/base.txt -r timeseries/deploy/requirements/dev.txt
      - name: Run the tests
        run: |
          trap '[ -n "$(jobs -pr)" ] && kill $(jobs -pr)' INT QUIT TERM EXIT
          cd timeseries
          ENVIRONMENT=dev pytest
