name: Test SKOPE Time Series API

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r deploy/requirements/base.txt -r deploy/requirements/dev.txt
          make -C tests node_modules
      - name: Run the tests
        run: |
          trap '[ -n "$(jobs -pr)" ] && kill $(jobs -pr)' INT QUIT TERM EXIT
          ENVIR=dev pytest
          ENVIR=dev uvicorn --port 8001 app.main:app &
          ./configure dev
          make test-integration
